version: '3.8'
services:
    
  # Application
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    working_dir: /var/www
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    volumes:
      - ./:/var/www
    depends_on:
      - "database"
  # Web Server
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - "app"
    ports:
      - 80:80
  # Database
  database:
    image: mysql:8.0
    volumes:
      - dbdata:/var/lib/mysql
    ports:
        - 33061:3306
  # Database management
  pma:
    image: phpmyadmin:5.1
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    depends_on:
      - database
    ports:
      - 8888:80

volumes:
  dbdata: