version: '3.8'
services:
    
  # Application
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    working_dir: /var/www/html
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    volumes:
      - ./:/var/www/html
    depends_on:
      - "db"
      
  # Web Server
  nginx:
    image: nginx:1.21.1-alpine
    container_name: nginx
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - "app"
    ports:
      - 80:80

  # Database
  db:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: mysql # db must be mysql
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  # Database management
  pma:
    image: phpmyadmin:5.0.2
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8081:80

volumes:
  dbdata: